# Generated by Django 4.1.3 on 2022-12-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=18)),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('celular', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('rol', models.CharField(max_length=15)),
            ],
        ),
    ]
