# Generated by Django 4.1.3 on 2022-12-20 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0002_alter_avatar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('animal', models.CharField(max_length=200)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotosmascotas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
