# Generated by Django 4.1.3 on 2022-12-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_mascotas_delete_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='edad',
            field=models.CharField(max_length=100),
        ),
    ]
