# Generated by Django 4.1.3 on 2022-12-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_mascotas_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotosmascotas'),
        ),
    ]
