# Generated by Django 4.1.3 on 2022-12-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_mascotas_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
                ('password', models.CharField(max_length=40)),
                ('verifypassword', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
