# Generated by Django 4.1.3 on 2022-12-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(max_length=500),
        ),
    ]
