<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-12-15 02:29
=======
# Generated by Django 4.1.3 on 2022-12-15 22:00
>>>>>>> a5f720760805820f272e87285614835c3b3af6ae

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_nada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Nada',
        ),
    ]
