# Generated by Django 4.1.4 on 2022-12-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_delete_nada'),
    ]

    operations = [
        migrations.CreateModel(
            name='nada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
    ]
