# Generated by Django 4.1.4 on 2022-12-18 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_nada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nada',
        ),
    ]
