# Generated by Django 4.1.4 on 2022-12-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=30)),
                ('contenido', models.CharField(max_length=1000)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Coments3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=30)),
                ('contenido', models.CharField(max_length=1000)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
