# Generated by Django 4.1.4 on 2022-12-16 00:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(default='Titulo', max_length=40)),
                ('Contenido', models.CharField(max_length=1000)),
                ('Fecha', models.DateField(default=datetime.datetime.now)),
                ('Destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destinatario', to=settings.AUTH_USER_MODEL)),
                ('Remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Remitente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
