# Generated by Django 4.1.4 on 2022-12-18 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0002_coments4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coments3',
        ),
        migrations.DeleteModel(
            name='Coments4',
        ),
    ]
