# Generated by Django 4.1.3 on 2022-12-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0002_remove_coment_destinatario_remove_coment_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='remitente',
            field=models.CharField(max_length=30),
        ),
    ]
