# Generated by Django 4.1.4 on 2022-12-18 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0002_remove_coments_remitente'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='remitente',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
