# Generated by Django 4.1.4 on 2022-12-18 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0002_remove_coments_algo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coments',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
