# Generated by Django 4.1.3 on 2022-12-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0003_alter_coment_remitente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comentario',
        ),
    ]
