# Generated by Django 4.1.4 on 2022-12-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0003_alter_coment_remitente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='remitente',
            field=models.CharField(max_length=30),
        ),
    ]
