# Generated by Django 4.1.4 on 2022-12-18 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0003_coments_remitente'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='algo',
            field=models.CharField(default=datetime.datetime(2022, 12, 18, 2, 56, 49, 393383, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
    ]
