# Generated by Django 4.1.4 on 2022-12-17 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comenapp', '0004_alter_coment_remitente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='Remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
