# Generated by Django 4.1.3 on 2022-12-17 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0004_rename_coment_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=30)),
                ('contenido', models.CharField(max_length=1000)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
