# Generated by Django 4.1.4 on 2022-12-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0004_remove_coments_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coments',
            name='remitente',
        ),
    ]
