# Generated by Django 4.1.3 on 2022-12-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0005_coment_delete_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='fecha',
            field=models.DateField(),
        ),
    ]
