# Generated by Django 4.1.4 on 2022-12-19 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0005_remove_coments_remitente'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='coments',
            name='remitente',
            field=models.CharField(default=datetime.datetime(2022, 12, 19, 18, 53, 50, 445068, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
