# Generated by Django 4.1.4 on 2022-12-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0004_alter_coment_remitente'),
        ('comenapp', '0006_alter_coment_fecha'),
    ]

    operations = [
    ]
