# Generated by Django 4.1.3 on 2022-12-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0006_alter_coment_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='fecha',
            field=models.IntegerField(),
        ),
    ]
