# Generated by Django 4.1.4 on 2022-12-19 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comenapp', '0006_coments_fecha_coments_remitente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coments',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
