# Generated by Django 4.1.4 on 2022-12-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0007_merge_20221217_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='Remitente',
        ),
        migrations.AlterField(
            model_name='coment',
            name='fecha',
            field=models.IntegerField(),
        ),
    ]
