# Generated by Django 4.1.3 on 2022-12-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comenapp', '0008_remove_coment_remitente_alter_coment_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=30)),
                ('contenido', models.CharField(max_length=1000)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Coment',
        ),
    ]
